"""autoria das notas da classificacao

Revisão: 7e21b15b6fef
Revisão anterior: 156af4c0e37e
Criada em: 2026-09-26 19:24:40.364530
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '7e21b15b6fef'
down_revision: str | None = '156af4c0e37e'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classificacao_do_grupo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atribuido_por', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('motivo', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classificacao_do_grupo', schema=None) as batch_op:
        batch_op.drop_column('motivo')
        batch_op.drop_column('atribuido_por')

    # ### end Alembic commands ###
