"""campos editados no crm

Revisão: a3084c28a83a
Revisão anterior: e53f6dcfc282
Criada em: 2026-09-21 17:34:45.686100
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a3084c28a83a'
down_revision: str | None = 'e53f6dcfc282'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campos_do_crm', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'[]'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidade', schema=None) as batch_op:
        batch_op.drop_column('campos_do_crm')

    # ### end Alembic commands ###
