"""período de avaliação e rascunho

Revisão: 8f8c7f3862e8
Revisão anterior: e270619bf426
Criada em: 2026-09-29 19:26:07.037039
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8f8c7f3862e8'
down_revision: str | None = 'e270619bf426'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodo_de_avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes_de_referencia', sa.Date(), nullable=False),
    sa.Column('aberto_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aberto_por', sa.String(length=120), nullable=False),
    sa.Column('margem_minima', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('margem_alvo', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('calculado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calculado_por', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_periodo_de_avaliacao')),
    sa.UniqueConstraint('mes_de_referencia', name=op.f('uq_periodo_de_avaliacao_mes_de_referencia'))
    )
    op.create_table('avaliacao_em_andamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('respostas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_por', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_economico.id'], name=op.f('fk_avaliacao_em_andamento_grupo_id_grupo_economico')),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo_de_avaliacao.id'], name=op.f('fk_avaliacao_em_andamento_periodo_id_periodo_de_avaliacao')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avaliacao_em_andamento')),
    sa.UniqueConstraint('periodo_id', 'grupo_id', name='uq_avaliacao_periodo_grupo')
    )
    with op.batch_alter_table('avaliacao_em_andamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avaliacao_em_andamento_grupo_id'), ['grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_avaliacao_em_andamento_periodo_id'), ['periodo_id'], unique=False)

    with op.batch_alter_table('grupo_economico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('porte_justificativa', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupo_economico', schema=None) as batch_op:
        batch_op.drop_column('porte_justificativa')

    with op.batch_alter_table('avaliacao_em_andamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avaliacao_em_andamento_periodo_id'))
        batch_op.drop_index(batch_op.f('ix_avaliacao_em_andamento_grupo_id'))

    op.drop_table('avaliacao_em_andamento')
    op.drop_table('periodo_de_avaliacao')
    # ### end Alembic commands ###
