"""sdr de ia: qualificacao do lead, conversas e custos

Revisão: 562856af0eb8
Revisão anterior: e1a2564337e7
Criada em: 2026-09-27 14:04:08.665862
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '562856af0eb8'
down_revision: str | None = 'e1a2564337e7'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investimento_em_midia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.String(length=7), nullable=False),
    sa.Column('canal', sa.String(length=120), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('valor >= 0', name=op.f('ck_investimento_em_midia_valor_nao_negativo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investimento_em_midia')),
    sa.UniqueConstraint('mes', 'canal', name='uq_investimento_mes_canal')
    )
    with op.batch_alter_table('investimento_em_midia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investimento_em_midia_mes'), ['mes'], unique=False)

    op.create_table('parametros_do_sdr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custo_hora_sdr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('minutos_por_conversa', sa.SmallInteger(), nullable=True),
    sa.Column('cotacao_dolar', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('atualizado_por', sa.String(length=10), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parametros_do_sdr'))
    )
    op.create_table('conversa_do_sdr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.Enum('E-mail', 'WhatsApp', name='canaldeabordagem', native_enum=False, length=40), nullable=False),
    sa.Column('iniciada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('encerrada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('desfecho', sa.Enum('Qualificado', 'Fora do perfil', 'Passou para a equipe', 'Parou no meio', name='desfechodaconversa', native_enum=False, length=40), nullable=True),
    sa.Column('motivo_transbordo', sa.Enum('Pediu para falar com uma pessoa', 'Perguntou o preço', 'Grupo com vários CNPJs', 'Dúvida técnica fora do roteiro', 'Lead irritado', 'Sistema externo fora do ar', 'Outro', name='motivodetransbordo', native_enum=False, length=60), nullable=True),
    sa.Column('destino_transbordo', sa.Enum('Comercial · BPO (C1)', 'Consultoria (C2)', 'Sócios · conta grande', 'Técnico fiscal', name='destinodotransbordo', native_enum=False, length=60), nullable=True),
    sa.Column('atendida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nota', sa.SmallInteger(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('nota IS NULL OR nota BETWEEN 1 AND 5', name=op.f('ck_conversa_do_sdr_nota_de_1_a_5')),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], name=op.f('fk_conversa_do_sdr_lead_id_lead')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversa_do_sdr'))
    )
    with op.batch_alter_table('conversa_do_sdr', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversa_do_sdr_iniciada_em'), ['iniciada_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversa_do_sdr_lead_id'), ['lead_id'], unique=False)

    op.create_table('mensagem_do_sdr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversa_id', sa.Integer(), nullable=False),
    sa.Column('autor', sa.Enum('Lead', 'IA', 'Equipe', name='autordamensagem', native_enum=False, length=40), nullable=False),
    sa.Column('enviada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('intencao', sa.String(length=120), nullable=True),
    sa.Column('confianca', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('fallback', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('termo_nao_reconhecido', sa.String(length=120), nullable=True),
    sa.Column('custo_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('tom', sa.Enum('Positivo', 'Neutro', 'Negativo', name='tom', native_enum=False, length=40), nullable=True),
    sa.CheckConstraint('confianca IS NULL OR confianca BETWEEN 0 AND 1', name=op.f('ck_mensagem_do_sdr_confianca_de_0_a_1')),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversa_do_sdr.id'], name=op.f('fk_mensagem_do_sdr_conversa_id_conversa_do_sdr')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mensagem_do_sdr'))
    )
    with op.batch_alter_table('mensagem_do_sdr', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mensagem_do_sdr_conversa_id'), ['conversa_id'], unique=False)

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj', sa.String(length=18), nullable=True))
        batch_op.add_column(sa.Column('porte_estimado', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('qualificado_em', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('descartado_em', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('motivo_descarte', sa.Enum('Porte abaixo do mínimo', 'Só quer serviço pontual', 'Já tem contador e não quer trocar agora', 'Pediu para não ser contatado', 'Segmento que a Critério não atende', 'Orçamento abaixo do piso', 'Outro', name='motivodedescarte', native_enum=False, length=60), nullable=True))
        batch_op.add_column(sa.Column('reuniao_marcada_para', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('nao_contatar', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('nao_contatar_em', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_column('nao_contatar_em')
        batch_op.drop_column('nao_contatar')
        batch_op.drop_column('reuniao_marcada_para')
        batch_op.drop_column('motivo_descarte')
        batch_op.drop_column('descartado_em')
        batch_op.drop_column('qualificado_em')
        batch_op.drop_column('porte_estimado')
        batch_op.drop_column('cnpj')

    with op.batch_alter_table('mensagem_do_sdr', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mensagem_do_sdr_conversa_id'))

    op.drop_table('mensagem_do_sdr')
    with op.batch_alter_table('conversa_do_sdr', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversa_do_sdr_lead_id'))
        batch_op.drop_index(batch_op.f('ix_conversa_do_sdr_iniciada_em'))

    op.drop_table('conversa_do_sdr')
    op.drop_table('parametros_do_sdr')
    with op.batch_alter_table('investimento_em_midia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investimento_em_midia_mes'))

    op.drop_table('investimento_em_midia')
    # ### end Alembic commands ###
