"""estrutura inicial: cliente, contato, lead e oportunidade

Revisão: dddbca46c445
Revisão anterior: 
Criada em: 2026-09-20 06:53:25.014591
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = 'dddbca46c445'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupo_economico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('situacao', sa.Enum('Prospect', 'Cliente', 'Encerrado', 'Fundido', name='situacaogrupo', native_enum=False, length=40), nullable=False),
    sa.Column('responsavel_cs', sa.String(length=10), nullable=True),
    sa.Column('data_entrada', sa.Date(), nullable=True),
    sa.Column('origem', sa.Enum('Carga 2026', 'CRM', name='origem', native_enum=False, length=40), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('fundido_em_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fundido_em_id IS NULL OR fundido_em_id <> id', name=op.f('ck_grupo_economico_nao_funde_em_si_mesmo')),
    sa.ForeignKeyConstraint(['fundido_em_id'], ['grupo_economico.id'], name=op.f('fk_grupo_economico_fundido_em_id_grupo_economico')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grupo_economico'))
    )
    with op.batch_alter_table('grupo_economico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grupo_economico_fundido_em_id'), ['fundido_em_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grupo_economico_nome'), ['nome'], unique=False)

    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('regime_tributario', sa.String(length=40), nullable=True),
    sa.Column('inscricao_estadual', sa.String(length=20), nullable=True),
    sa.Column('inscricao_municipal', sa.String(length=20), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('situacao', sa.Enum('Ativa', 'Inativa', 'Baixada', name='situacaoempresa', native_enum=False, length=40), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_economico.id'], name=op.f('fk_empresa_grupo_id_grupo_economico')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresa'))
    )
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresa_cnpj'), ['cnpj'], unique=True)
        batch_op.create_index(batch_op.f('ix_empresa_grupo_id'), ['grupo_id'], unique=False)

    op.create_table('oportunidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('servico', sa.String(length=120), nullable=True),
    sa.Column('tipo_servico', sa.String(length=120), nullable=True),
    sa.Column('linha_servico', sa.Enum('C1', 'C2', name='linhaservico', native_enum=False, length=40), nullable=True),
    sa.Column('tipo_canal', sa.Enum('Sócios', 'Parceiros', 'Advogados', 'Carteira', 'Interno', 'Colaboradores', 'Tráfego pago', 'Afiliados', name='tipocanal', native_enum=False, length=40), nullable=True),
    sa.Column('canal', sa.String(length=120), nullable=True),
    sa.Column('captador', sa.String(length=10), nullable=True),
    sa.Column('situacao', sa.Enum('Enviar proposta', 'Em avaliação pela empresa', 'On hold', 'Aceita', 'Recusada', 'Perdido', name='situacao', native_enum=False, length=40), nullable=False),
    sa.Column('temperatura', sa.Enum('Frio', 'Morno', 'Quente', name='temperatura', native_enum=False, length=40), nullable=True),
    sa.Column('data_colocacao', sa.Date(), nullable=True),
    sa.Column('data_aceite', sa.Date(), nullable=True),
    sa.Column('motivo_recusa', sa.Enum('Preço', 'Sem retorno', 'Desistência', 'Cliente internalizou', 'Concorrência', 'Momento', 'Escopo', 'Pro bono', 'Outro', name='motivorecusa', native_enum=False, length=40), nullable=True),
    sa.Column('motivo_recusa_original', sa.String(length=200), nullable=True),
    sa.Column('preco_mensal', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('preco_anual', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valor_mensalizado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('proxima_acao', sa.String(length=200), nullable=True),
    sa.Column('proxima_acao_em', sa.Date(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('origem', sa.Enum('Carga 2026', 'CRM', name='origem', native_enum=False, length=40), nullable=False),
    sa.Column('chave_origem', sa.String(length=400), nullable=True),
    sa.Column('linha_planilha', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("origem <> 'Carga 2026' OR chave_origem IS NOT NULL", name=op.f('ck_oportunidade_carga_exige_chave_de_origem')),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_economico.id'], name=op.f('fk_oportunidade_grupo_id_grupo_economico')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oportunidade'))
    )
    with op.batch_alter_table('oportunidade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oportunidade_captador'), ['captador'], unique=False)
        batch_op.create_index(batch_op.f('ix_oportunidade_chave_origem'), ['chave_origem'], unique=True)
        batch_op.create_index(batch_op.f('ix_oportunidade_data_colocacao'), ['data_colocacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_oportunidade_grupo_id'), ['grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oportunidade_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_oportunidade_proxima_acao_em'), ['proxima_acao_em'], unique=False)

    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('empresa_texto', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('tipo_canal', sa.Enum('Sócios', 'Parceiros', 'Advogados', 'Carteira', 'Interno', 'Colaboradores', 'Tráfego pago', 'Afiliados', name='tipocanal', native_enum=False, length=40), nullable=True),
    sa.Column('canal', sa.String(length=120), nullable=True),
    sa.Column('captador', sa.String(length=10), nullable=True),
    sa.Column('interesse', sa.String(length=200), nullable=True),
    sa.Column('temperatura', sa.Enum('Frio', 'Morno', 'Quente', name='temperatura', native_enum=False, length=40), nullable=True),
    sa.Column('situacao', sa.Enum('Novo', 'Em contato', 'Qualificado', 'Convertido', 'Descartado', name='situacaolead', native_enum=False, length=40), nullable=False),
    sa.Column('campanha', sa.String(length=120), nullable=True),
    sa.Column('campanha_midia', sa.String(length=120), nullable=True),
    sa.Column('proxima_acao', sa.String(length=200), nullable=True),
    sa.Column('proxima_acao_em', sa.Date(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('convertido_em_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['convertido_em_id'], ['oportunidade.id'], name=op.f('fk_lead_convertido_em_id_oportunidade')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead'))
    )
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_convertido_em_id'), ['convertido_em_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_proxima_acao_em'), ['proxima_acao_em'], unique=False)

    op.create_table('pessoa_contato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('papel', sa.Enum('Decisor', 'Influenciador', 'Usuário', 'Ponto focal', name='papelcontato', native_enum=False, length=40), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('nao_contatar', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('nao_contatar_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nao_contatar_motivo', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('grupo_id IS NOT NULL OR empresa_id IS NOT NULL', name=op.f('ck_pessoa_contato_contato_pertence_a_alguem')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_pessoa_contato_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_economico.id'], name=op.f('fk_pessoa_contato_grupo_id_grupo_economico')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pessoa_contato'))
    )
    with op.batch_alter_table('pessoa_contato', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pessoa_contato_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_pessoa_contato_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pessoa_contato_grupo_id'), ['grupo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa_contato', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pessoa_contato_grupo_id'))
        batch_op.drop_index(batch_op.f('ix_pessoa_contato_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_pessoa_contato_email'))

    op.drop_table('pessoa_contato')
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_proxima_acao_em'))
        batch_op.drop_index(batch_op.f('ix_lead_nome'))
        batch_op.drop_index(batch_op.f('ix_lead_convertido_em_id'))

    op.drop_table('lead')
    with op.batch_alter_table('oportunidade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oportunidade_proxima_acao_em'))
        batch_op.drop_index(batch_op.f('ix_oportunidade_nome'))
        batch_op.drop_index(batch_op.f('ix_oportunidade_grupo_id'))
        batch_op.drop_index(batch_op.f('ix_oportunidade_data_colocacao'))
        batch_op.drop_index(batch_op.f('ix_oportunidade_chave_origem'))
        batch_op.drop_index(batch_op.f('ix_oportunidade_captador'))

    op.drop_table('oportunidade')
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresa_grupo_id'))
        batch_op.drop_index(batch_op.f('ix_empresa_cnpj'))

    op.drop_table('empresa')
    with op.batch_alter_table('grupo_economico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grupo_economico_nome'))
        batch_op.drop_index(batch_op.f('ix_grupo_economico_fundido_em_id'))

    op.drop_table('grupo_economico')
    # ### end Alembic commands ###
