"""iniciativa do encerramento

Revisão: c6a727f3ba73
Revisão anterior: 2042b068186f
Criada em: 2026-09-26 15:52:40.150084
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = 'c6a727f3ba73'
down_revision: str | None = '2042b068186f'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_de_contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iniciativa', sa.Enum('Cliente', 'Critério', name='iniciativadoencerramento', native_enum=False, length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_evento_de_contrato_iniciativa'), ['iniciativa'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_de_contrato', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evento_de_contrato_iniciativa'))
        batch_op.drop_column('iniciativa')

    # ### end Alembic commands ###
