"""volumetria e porte na carteira

Revisão: 412f596570dc
Revisão anterior: e1a2564337e7
Criada em: 2026-09-27 15:15:47.260122
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '412f596570dc'
down_revision: str | None = 'e1a2564337e7'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupo_economico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documentos_fiscais_mes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lancamentos_contabeis_mes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pagamentos_mes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contas_bancarias', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('conciliacoes_cartao_mes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('empregados_clt', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admissoes_desligamentos_mes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cnpjs_no_escopo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tomadores_de_servico', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('servicos_contratados_alem_do_primeiro', sa.SmallInteger(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('tem_consolidacao_de_grupo', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('e_auditada', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('porte', sa.String(length=20), nullable=True))
        # 120, não 10 como em oportunidade.porte_definido_por (lá é iniciais; aqui é o mesmo campo
        # "autor" de nome completo que /notas já usa — mesma pessoa, mesmo painel de avaliação).
        batch_op.add_column(sa.Column('porte_definido_por', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('porte_definido_em', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupo_economico', schema=None) as batch_op:
        batch_op.drop_column('porte_definido_em')
        batch_op.drop_column('porte_definido_por')
        batch_op.drop_column('porte')
        batch_op.drop_column('e_auditada')
        batch_op.drop_column('tem_consolidacao_de_grupo')
        batch_op.drop_column('servicos_contratados_alem_do_primeiro')
        batch_op.drop_column('tomadores_de_servico')
        batch_op.drop_column('cnpjs_no_escopo')
        batch_op.drop_column('admissoes_desligamentos_mes')
        batch_op.drop_column('empregados_clt')
        batch_op.drop_column('conciliacoes_cartao_mes')
        batch_op.drop_column('contas_bancarias')
        batch_op.drop_column('pagamentos_mes')
        batch_op.drop_column('lancamentos_contabeis_mes')
        batch_op.drop_column('documentos_fiscais_mes')

    # ### end Alembic commands ###
