"""questionário recebido do site

Revisão: 3b26e19f7eeb
Revisão anterior: 8f8c7f3862e8
Criada em: 2026-10-01 07:11:10.904699
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3b26e19f7eeb'
down_revision: str | None = '8f8c7f3862e8'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionario_recebido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('externo_id', sa.String(length=64), nullable=False),
    sa.Column('recebido_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('versao', sa.String(length=60), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('contato_nome', sa.String(length=200), nullable=False),
    sa.Column('contato_cargo', sa.String(length=100), nullable=True),
    sa.Column('contato_celular', sa.String(length=30), nullable=True),
    sa.Column('contato_email', sa.String(length=200), nullable=True),
    sa.Column('respostas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('avaliacao_do_site', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('pdf_base64', sa.Text(), nullable=True),
    sa.Column('situacao', sa.Enum('Importado', 'Precisa de você', name='situacaodoquestionario', native_enum=False, length=40), nullable=False),
    sa.Column('o_que_fez', sa.Text(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('oportunidade_id', sa.Integer(), nullable=True),
    sa.Column('oportunidade_em_aberto_id', sa.Integer(), nullable=True),
    sa.Column('cliente_novo', sa.Boolean(), nullable=False),
    sa.Column('porte_crm', sa.String(length=20), nullable=True),
    sa.Column('porte_site', sa.String(length=20), nullable=True),
    sa.Column('marcado_na_origem_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_economico.id'], name=op.f('fk_questionario_recebido_grupo_id_grupo_economico')),
    sa.ForeignKeyConstraint(['oportunidade_em_aberto_id'], ['oportunidade.id'], name=op.f('fk_questionario_recebido_oportunidade_em_aberto_id_oportunidade')),
    sa.ForeignKeyConstraint(['oportunidade_id'], ['oportunidade.id'], name=op.f('fk_questionario_recebido_oportunidade_id_oportunidade')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questionario_recebido')),
    sa.UniqueConstraint('externo_id', name=op.f('uq_questionario_recebido_externo_id'))
    )
    with op.batch_alter_table('questionario_recebido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questionario_recebido_cnpj'), ['cnpj'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionario_recebido_grupo_id'), ['grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionario_recebido_oportunidade_id'), ['oportunidade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionario_recebido_recebido_em'), ['recebido_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionario_recebido_situacao'), ['situacao'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionario_recebido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questionario_recebido_situacao'))
        batch_op.drop_index(batch_op.f('ix_questionario_recebido_recebido_em'))
        batch_op.drop_index(batch_op.f('ix_questionario_recebido_oportunidade_id'))
        batch_op.drop_index(batch_op.f('ix_questionario_recebido_grupo_id'))
        batch_op.drop_index(batch_op.f('ix_questionario_recebido_cnpj'))

    op.drop_table('questionario_recebido')
    # ### end Alembic commands ###
