"""respostas da avaliação

Revisão: e270619bf426
Revisão anterior: 5dc8a026d67a
Criada em: 2026-09-29 18:47:27.140405
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e270619bf426'
down_revision: str | None = '5dc8a026d67a'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classificacao_do_grupo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respostas_da_avaliacao', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classificacao_do_grupo', schema=None) as batch_op:
        batch_op.drop_column('respostas_da_avaliacao')

    # ### end Alembic commands ###
