"""revisao da classificacao

Revisão: 156af4c0e37e
Revisão anterior: 6857edd15050
Criada em: 2026-09-26 18:58:46.137351
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '156af4c0e37e'
down_revision: str | None = '6857edd15050'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classificacao_do_grupo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revisao', sa.SmallInteger(), server_default='1', nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_classificacao_grupo_referencia'), type_='unique')
        batch_op.create_unique_constraint('uq_classificacao_grupo_referencia', ['grupo_id', 'referencia', 'revisao'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classificacao_do_grupo', schema=None) as batch_op:
        batch_op.drop_constraint('uq_classificacao_grupo_referencia', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_classificacao_grupo_referencia'), ['grupo_id', 'referencia'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('revisao')

    # ### end Alembic commands ###
