"""agente SDR: ficha da conta, abordagem e execucao do agente

Revisão: 8673eda1df27
Revisão anterior: 33f52c219e28
Criada em: 2026-09-26 20:06:20.629336
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8673eda1df27'
down_revision: str | None = '33f52c219e28'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ficha_de_conta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('historico', sa.Text(), nullable=False),
    sa.Column('pesquisa', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('quem_decide', sa.String(length=300), nullable=True),
    sa.Column('modelo', sa.String(length=60), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_economico.id'], name=op.f('fk_ficha_de_conta_grupo_id_grupo_economico')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ficha_de_conta'))
    )
    with op.batch_alter_table('ficha_de_conta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ficha_de_conta_grupo_id'), ['grupo_id'], unique=False)

    op.create_table('abordagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.String(length=7), nullable=False),
    sa.Column('quem_apresenta', sa.String(length=120), nullable=True),
    sa.Column('contexto', sa.Text(), nullable=True),
    sa.Column('canal', sa.Enum('E-mail', 'WhatsApp', name='canaldeabordagem', native_enum=False, length=40), nullable=False),
    sa.Column('destinatario', sa.String(length=200), nullable=True),
    sa.Column('assunto', sa.String(length=300), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('versao', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('situacao', sa.Enum('A preparar', 'Pesquisando', 'Aguardando aprovação', 'Aprovada', 'Enviada', 'Descartada', 'Erro', 'Bloqueada', name='situacaoabordagem', native_enum=False, length=40), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('ficha_id', sa.Integer(), nullable=True),
    sa.Column('aprovada_por', sa.String(length=10), nullable=True),
    sa.Column('aprovada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enviada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('diagnostico_agendado_em', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ficha_id'], ['ficha_de_conta.id'], name=op.f('fk_abordagem_ficha_id_ficha_de_conta')),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_economico.id'], name=op.f('fk_abordagem_grupo_id_grupo_economico')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_abordagem'))
    )
    with op.batch_alter_table('abordagem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_abordagem_grupo_id'), ['grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_abordagem_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_abordagem_situacao'), ['situacao'], unique=False)

    op.create_table('execucao_do_agente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abordagem_id', sa.Integer(), nullable=False),
    sa.Column('iniciada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terminada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modelo', sa.String(length=60), nullable=False),
    sa.Column('tokens_entrada', sa.Integer(), nullable=False),
    sa.Column('tokens_saida', sa.Integer(), nullable=False),
    sa.Column('buscas_web', sa.Integer(), nullable=False),
    sa.Column('custo_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('deu_certo', sa.Boolean(), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['abordagem_id'], ['abordagem.id'], name=op.f('fk_execucao_do_agente_abordagem_id_abordagem')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execucao_do_agente'))
    )
    with op.batch_alter_table('execucao_do_agente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execucao_do_agente_abordagem_id'), ['abordagem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execucao_do_agente_iniciada_em'), ['iniciada_em'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execucao_do_agente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execucao_do_agente_iniciada_em'))
        batch_op.drop_index(batch_op.f('ix_execucao_do_agente_abordagem_id'))

    op.drop_table('execucao_do_agente')
    with op.batch_alter_table('abordagem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_abordagem_situacao'))
        batch_op.drop_index(batch_op.f('ix_abordagem_mes'))
        batch_op.drop_index(batch_op.f('ix_abordagem_grupo_id'))

    op.drop_table('abordagem')
    with op.batch_alter_table('ficha_de_conta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ficha_de_conta_grupo_id'))

    op.drop_table('ficha_de_conta')
    # ### end Alembic commands ###
