"""registro de fusao de grupos

Revisão: 26e2cc62ead2
Revisão anterior: 8673eda1df27
Criada em: 2026-09-26 18:03:51.922452
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '26e2cc62ead2'
down_revision: str | None = '8673eda1df27'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fusao_de_grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principal_id', sa.Integer(), nullable=False),
    sa.Column('absorvido_id', sa.Integer(), nullable=False),
    sa.Column('feita_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('desfeita_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconstruida', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('movidos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('absorvido_situacao_antes', sa.String(length=40), nullable=False),
    sa.Column('principal_situacao_antes', sa.String(length=40), nullable=False),
    sa.Column('principal_situacao_depois', sa.String(length=40), nullable=False),
    sa.Column('principal_data_entrada_antes', sa.Date(), nullable=True),
    sa.Column('principal_data_entrada_depois', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['absorvido_id'], ['grupo_economico.id'], name=op.f('fk_fusao_de_grupos_absorvido_id_grupo_economico')),
    sa.ForeignKeyConstraint(['principal_id'], ['grupo_economico.id'], name=op.f('fk_fusao_de_grupos_principal_id_grupo_economico')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fusao_de_grupos'))
    )
    with op.batch_alter_table('fusao_de_grupos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fusao_de_grupos_absorvido_id'), ['absorvido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fusao_de_grupos_principal_id'), ['principal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fusao_de_grupos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fusao_de_grupos_principal_id'))
        batch_op.drop_index(batch_op.f('ix_fusao_de_grupos_absorvido_id'))

    op.drop_table('fusao_de_grupos')
    # ### end Alembic commands ###
