"""tema do servico

Revisão: a3727af424db
Revisão anterior: a96818a796a7
Criada em: 2026-09-27 21:00:52.406940
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = 'a3727af424db'
down_revision: str | None = 'a96818a796a7'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interesse_tema', sa.String(length=80), nullable=True))

    with op.batch_alter_table('oportunidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servico_tema', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidade', schema=None) as batch_op:
        batch_op.drop_column('servico_tema')

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_column('interesse_tema')

    # ### end Alembic commands ###
