"""versão de parâmetros e mix de equipe editáveis

Revisão: 5dc8a026d67a
Revisão anterior: a3727af424db
Criada em: 2026-09-28 07:53:17.262255
"""

from __future__ import annotations

from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa


revision: str = '5dc8a026d67a'
down_revision: str | None = 'a3727af424db'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versao_de_parametros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('autor', sa.String(length=120), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('peso_receita', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('peso_rentabilidade', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('peso_cross_sell', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('peso_complexidade', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('peso_disciplina', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('peso_risco', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('peso_adimplencia', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('corte_a', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('corte_b', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('trava_de_adimplencia', sa.SmallInteger(), nullable=False),
    sa.Column('churn_alto', sa.SmallInteger(), nullable=False),
    sa.Column('imposto', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('teto_de_atrito', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('atrito_nota_1', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('atrito_nota_2', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('atrito_nota_3', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('atrito_nota_4', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('atrito_nota_5', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('corte_margem_2', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('corte_margem_3', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('corte_margem_4', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('corte_margem_5', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('horas_micro', sa.SmallInteger(), nullable=False),
    sa.Column('horas_pequeno', sa.SmallInteger(), nullable=False),
    sa.Column('horas_medio', sa.SmallInteger(), nullable=False),
    sa.Column('horas_grande', sa.SmallInteger(), nullable=False),
    sa.Column('horas_extra_grande', sa.SmallInteger(), nullable=False),
    sa.Column('taxa_socio_senior', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxa_socio_junior', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxa_supervisor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxa_analista_senior', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxa_analista_pleno', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxa_analista_junior', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_versao_de_parametros'))
    )
    with op.batch_alter_table('versao_de_parametros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_versao_de_parametros_criado_em'), ['criado_em'], unique=False)

    op.create_table('mix_de_equipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('versao_id', sa.Integer(), nullable=False),
    sa.Column('porte', sa.String(length=20), nullable=False),
    sa.Column('cargo', sa.String(length=30), nullable=False),
    sa.Column('mix_percentual', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['versao_id'], ['versao_de_parametros.id'], name=op.f('fk_mix_de_equipe_versao_id_versao_de_parametros')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mix_de_equipe')),
    sa.UniqueConstraint('versao_id', 'porte', 'cargo', name='uq_mix_versao_porte_cargo')
    )
    with op.batch_alter_table('mix_de_equipe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mix_de_equipe_versao_id'), ['versao_id'], unique=False)

    # ### end Alembic commands ###

    # Semente: a primeira versão é exatamente o que já estava fixo no código (Parametros e
    # ParametrosDeRentabilidade), conferido célula a célula contra Classificacao_Grupo_COMPLETO.xlsx
    # (aba Parâmetros) e Rentabilidade_Grupo_COMPLETO.xlsx (abas "2. Matriz Horas", "3. Fator de
    # Atrito" e "6. Régua Rentab.") em 28/09/2026 — nenhum valor novo, só sai do código pro banco.
    versao_de_parametros = sa.table(
        'versao_de_parametros', sa.column('id', sa.Integer), sa.column('criado_em', sa.DateTime(timezone=True)),
        sa.column('autor', sa.String), sa.column('motivo', sa.String),
        sa.column('peso_receita', sa.Numeric), sa.column('peso_rentabilidade', sa.Numeric),
        sa.column('peso_cross_sell', sa.Numeric), sa.column('peso_complexidade', sa.Numeric),
        sa.column('peso_disciplina', sa.Numeric), sa.column('peso_risco', sa.Numeric),
        sa.column('peso_adimplencia', sa.Numeric), sa.column('corte_a', sa.Numeric), sa.column('corte_b', sa.Numeric),
        sa.column('trava_de_adimplencia', sa.SmallInteger), sa.column('churn_alto', sa.SmallInteger),
        sa.column('imposto', sa.Numeric), sa.column('teto_de_atrito', sa.Numeric),
        sa.column('atrito_nota_1', sa.Numeric), sa.column('atrito_nota_2', sa.Numeric),
        sa.column('atrito_nota_3', sa.Numeric), sa.column('atrito_nota_4', sa.Numeric), sa.column('atrito_nota_5', sa.Numeric),
        sa.column('corte_margem_2', sa.Numeric), sa.column('corte_margem_3', sa.Numeric),
        sa.column('corte_margem_4', sa.Numeric), sa.column('corte_margem_5', sa.Numeric),
        sa.column('horas_micro', sa.SmallInteger), sa.column('horas_pequeno', sa.SmallInteger),
        sa.column('horas_medio', sa.SmallInteger), sa.column('horas_grande', sa.SmallInteger),
        sa.column('horas_extra_grande', sa.SmallInteger),
        sa.column('taxa_socio_senior', sa.Numeric), sa.column('taxa_socio_junior', sa.Numeric),
        sa.column('taxa_supervisor', sa.Numeric), sa.column('taxa_analista_senior', sa.Numeric),
        sa.column('taxa_analista_pleno', sa.Numeric), sa.column('taxa_analista_junior', sa.Numeric),
    )
    conexao = op.get_bind()
    resultado = conexao.execute(
        versao_de_parametros.insert().values(
            criado_em=datetime.now(timezone.utc),
            autor="Migração automática",
            motivo="Semente inicial: valores já vigentes no código, conferidos contra as planilhas em 28/09/2026.",
            peso_receita=0.20, peso_rentabilidade=0.25, peso_cross_sell=0.12, peso_complexidade=0.12,
            peso_disciplina=0.09, peso_risco=0.07, peso_adimplencia=0.15, corte_a=3.95, corte_b=3.35,
            trava_de_adimplencia=2, churn_alto=4,
            imposto=0.11, teto_de_atrito=1.5,
            atrito_nota_1=0, atrito_nota_2=0.05, atrito_nota_3=0.10, atrito_nota_4=0.30, atrito_nota_5=0.50,
            corte_margem_2=0.30, corte_margem_3=0.45, corte_margem_4=0.60, corte_margem_5=0.70,
            horas_micro=5, horas_pequeno=10, horas_medio=16, horas_grande=40, horas_extra_grande=80,
            taxa_socio_senior=93.75, taxa_socio_junior=106.25, taxa_supervisor=75.00,
            taxa_analista_senior=50.00, taxa_analista_pleno=31.25, taxa_analista_junior=18.75,
        ).returning(versao_de_parametros.c.id)
    )
    versao_id = resultado.scalar_one()

    mix_de_equipe = sa.table(
        'mix_de_equipe', sa.column('versao_id', sa.Integer), sa.column('porte', sa.String),
        sa.column('cargo', sa.String), sa.column('mix_percentual', sa.Numeric),
    )
    mix_por_porte = {
        "Micro": {"Sócio Sênior": 0, "Sócio Júnior/Gerente": 0.01, "Supervisor/Especialista": 0.02,
                  "Analista Sênior": 0.47, "Analista Pleno": 0.50, "Analista Júnior": 0},
        "Pequeno": {"Sócio Sênior": 0, "Sócio Júnior/Gerente": 0.01, "Supervisor/Especialista": 0.02,
                    "Analista Sênior": 0.47, "Analista Pleno": 0.50, "Analista Júnior": 0},
        "Médio": {"Sócio Sênior": 0, "Sócio Júnior/Gerente": 0.01, "Supervisor/Especialista": 0.08,
                  "Analista Sênior": 0.30, "Analista Pleno": 0.51, "Analista Júnior": 0.10},
        "Grande": {"Sócio Sênior": 0.01, "Sócio Júnior/Gerente": 0.01, "Supervisor/Especialista": 0.09,
                   "Analista Sênior": 0.30, "Analista Pleno": 0.43, "Analista Júnior": 0.16},
        "Extra Grande": {"Sócio Sênior": 0.02, "Sócio Júnior/Gerente": 0.05, "Supervisor/Especialista": 0.13,
                          "Analista Sênior": 0.30, "Analista Pleno": 0.30, "Analista Júnior": 0.20},
    }
    conexao.execute(mix_de_equipe.insert(), [
        {"versao_id": versao_id, "porte": porte, "cargo": cargo, "mix_percentual": valor}
        for porte, cargos in mix_por_porte.items()
        for cargo, valor in cargos.items()
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mix_de_equipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mix_de_equipe_versao_id'))

    op.drop_table('mix_de_equipe')
    with op.batch_alter_table('versao_de_parametros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_versao_de_parametros_criado_em'))

    op.drop_table('versao_de_parametros')
    # ### end Alembic commands ###
