"""relatorio de conferencia da carga

Revisão: e53f6dcfc282
Revisão anterior: 57a039d70ed5
Criada em: 2026-09-21 17:26:47.272018
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = 'e53f6dcfc282'
down_revision: str | None = '57a039d70ed5'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execucao_de_carga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arquivo', sa.String(length=300), nullable=False),
    sa.Column('lidas', sa.Integer(), nullable=False),
    sa.Column('de_outro_ano', sa.Integer(), nullable=False),
    sa.Column('residuais', sa.Integer(), nullable=False),
    sa.Column('importadas', sa.Integer(), nullable=False),
    sa.Column('criadas', sa.Integer(), nullable=False),
    sa.Column('atualizadas', sa.Integer(), nullable=False),
    sa.Column('inalteradas', sa.Integer(), nullable=False),
    sa.Column('ignoradas_incompletas', sa.Integer(), nullable=False),
    sa.Column('ignoradas_duplicatas', sa.Integer(), nullable=False),
    sa.Column('grupos_criados', sa.Integer(), nullable=False),
    sa.Column('grupos_reaproveitados', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execucao_de_carga'))
    )
    with op.batch_alter_table('execucao_de_carga', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execucao_de_carga_executada_em'), ['executada_em'], unique=False)

    op.create_table('ocorrencia_de_carga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execucao_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('Precisa de você', 'Ajustado sozinho', 'Mudou na recarga', name='tipodeocorrencia', native_enum=False, length=40), nullable=False),
    sa.Column('linha', sa.Integer(), nullable=True),
    sa.Column('campo', sa.String(length=60), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucao_de_carga.id'], name=op.f('fk_ocorrencia_de_carga_execucao_id_execucao_de_carga')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ocorrencia_de_carga'))
    )
    with op.batch_alter_table('ocorrencia_de_carga', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocorrencia_de_carga_execucao_id'), ['execucao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ocorrencia_de_carga_tipo'), ['tipo'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocorrencia_de_carga', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocorrencia_de_carga_tipo'))
        batch_op.drop_index(batch_op.f('ix_ocorrencia_de_carga_execucao_id'))

    op.drop_table('ocorrencia_de_carga')
    with op.batch_alter_table('execucao_de_carga', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execucao_de_carga_executada_em'))

    op.drop_table('execucao_de_carga')
    # ### end Alembic commands ###
