"""regua de porte e volumetria na oportunidade

Revisão: 6e1cba3aca1d
Revisão anterior: a3084c28a83a
Criada em: 2026-09-23 02:37:33.159992
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '6e1cba3aca1d'
down_revision: str | None = 'a3084c28a83a'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complexidade', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('risco_tecnico', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('documentos_fiscais_mes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lancamentos_contabeis_mes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pagamentos_mes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contas_bancarias', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('conciliacoes_cartao_mes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('empregados_clt', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admissoes_desligamentos_mes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cnpjs_no_escopo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tomadores_de_servico', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('servicos_contratados_alem_do_primeiro', sa.SmallInteger(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('tem_consolidacao_de_grupo', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('e_auditada', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('porte', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('porte_definido_por', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('porte_definido_em', sa.DateTime(timezone=True), nullable=True))
        # Autogenerate não detecta CheckConstraint novo em tabela existente —
        # os dois abaixo entraram à mão.
        batch_op.create_check_constraint(
            'complexidade_de_1_a_5', 'complexidade IS NULL OR complexidade BETWEEN 1 AND 5'
        )
        batch_op.create_check_constraint(
            'risco_tecnico_de_1_a_5', 'risco_tecnico IS NULL OR risco_tecnico BETWEEN 1 AND 5'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidade', schema=None) as batch_op:
        batch_op.drop_constraint('risco_tecnico_de_1_a_5', type_='check')
        batch_op.drop_constraint('complexidade_de_1_a_5', type_='check')
        batch_op.drop_column('porte_definido_em')
        batch_op.drop_column('porte_definido_por')
        batch_op.drop_column('porte')
        batch_op.drop_column('e_auditada')
        batch_op.drop_column('tem_consolidacao_de_grupo')
        batch_op.drop_column('servicos_contratados_alem_do_primeiro')
        batch_op.drop_column('tomadores_de_servico')
        batch_op.drop_column('cnpjs_no_escopo')
        batch_op.drop_column('admissoes_desligamentos_mes')
        batch_op.drop_column('empregados_clt')
        batch_op.drop_column('conciliacoes_cartao_mes')
        batch_op.drop_column('contas_bancarias')
        batch_op.drop_column('pagamentos_mes')
        batch_op.drop_column('lancamentos_contabeis_mes')
        batch_op.drop_column('documentos_fiscais_mes')
        batch_op.drop_column('risco_tecnico')
        batch_op.drop_column('complexidade')

    # ### end Alembic commands ###
