"""analise da carteira

Revisão: 1d8ac660302d
Revisão anterior: 7e21b15b6fef
Criada em: 2026-09-27 07:51:06.254689
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '1d8ac660302d'
down_revision: str | None = '7e21b15b6fef'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analise_da_carteira',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gerada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gerada_por', sa.String(length=120), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('modelo', sa.String(length=60), nullable=False),
    sa.Column('tokens_entrada', sa.Integer(), nullable=False),
    sa.Column('tokens_saida', sa.Integer(), nullable=False),
    sa.Column('custo_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analise_da_carteira'))
    )
    with op.batch_alter_table('analise_da_carteira', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analise_da_carteira_gerada_em'), ['gerada_em'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analise_da_carteira', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analise_da_carteira_gerada_em'))

    op.drop_table('analise_da_carteira')
    # ### end Alembic commands ###
