"""cria contrato, comeco da etapa 2

Revisão: a701e6cc6b34
Revisão anterior: 6e1cba3aca1d
Criada em: 2026-09-23 07:48:37.314930
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = 'a701e6cc6b34'
down_revision: str | None = '6e1cba3aca1d'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('oportunidade_id', sa.Integer(), nullable=True),
    sa.Column('escopo', sa.String(length=200), nullable=True),
    sa.Column('preco_mensal', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('preco_anual', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('situacao', sa.Enum('Aguardando assinatura', 'Ativo', 'Suspenso', 'Encerrado', name='situacaocontrato', native_enum=False, length=40), nullable=False),
    sa.Column('documento_assinado', sa.String(length=400), nullable=True),
    sa.Column('signatario', sa.String(length=200), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_economico.id'], name=op.f('fk_contrato_grupo_id_grupo_economico')),
    sa.ForeignKeyConstraint(['oportunidade_id'], ['oportunidade.id'], name=op.f('fk_contrato_oportunidade_id_oportunidade')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contrato'))
    )
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contrato_grupo_id'), ['grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contrato_oportunidade_id'), ['oportunidade_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contrato_oportunidade_id'))
        batch_op.drop_index(batch_op.f('ix_contrato_grupo_id'))

    op.drop_table('contrato')
    # ### end Alembic commands ###
