"""descricao do servico fora do catalogo

Revisão: bf638b8cce5f
Revisão anterior: 562856af0eb8
Criada em: 2026-09-27 19:43:07.536182
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = 'bf638b8cce5f'
down_revision: str | None = '562856af0eb8'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interesse_descricao', sa.Text(), nullable=True))

    with op.batch_alter_table('oportunidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servico_descricao', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidade', schema=None) as batch_op:
        batch_op.drop_column('servico_descricao')

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_column('interesse_descricao')

    # ### end Alembic commands ###
