"""proposta em powerpoint

Revisão: 3e2336222a59
Revisão anterior: 3b26e19f7eeb
Criada em: 2026-10-01 08:19:41.693579
"""

from __future__ import annotations

from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3e2336222a59'
down_revision: str | None = '3b26e19f7eeb'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao_de_proposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proximo_numero', sa.Integer(), nullable=False),
    sa.Column('revisores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('plano_bpo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('plano_plus', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('plano_cfo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuracao_de_proposta'))
    )
    op.create_table('matriz_de_proposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('Contábil', 'Financeiro', name='tipodematriz', native_enum=False, length=40), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=200), nullable=False),
    sa.Column('conteudo_base64', sa.Text(), nullable=False),
    sa.Column('enviada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enviada_por', sa.String(length=60), nullable=False),
    sa.Column('faltando', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('desconhecidos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matriz_de_proposta'))
    )
    with op.batch_alter_table('matriz_de_proposta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matriz_de_proposta_tipo'), ['tipo'], unique=False)

    op.create_table('proposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oportunidade_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('ano', sa.SmallInteger(), nullable=False),
    sa.Column('matriz_id', sa.Integer(), nullable=False),
    sa.Column('valores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('valor_liquido', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valor_bruto', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gerada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enviada_em', sa.Date(), nullable=True),
    sa.Column('enviada_por', sa.String(length=60), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['matriz_id'], ['matriz_de_proposta.id'], name=op.f('fk_proposta_matriz_id_matriz_de_proposta')),
    sa.ForeignKeyConstraint(['oportunidade_id'], ['oportunidade.id'], name=op.f('fk_proposta_oportunidade_id_oportunidade')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposta')),
    sa.UniqueConstraint('ano', 'numero', name='uq_proposta_ano_numero')
    )
    with op.batch_alter_table('proposta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposta_oportunidade_id'), ['oportunidade_id'], unique=False)

    # ### end Alembic commands ###

    # A sequência continua de onde a planilha parou: a última enviada foi a 153.2026 (NRH).
    # Aprovado por Eduardo em 01/10/2026.
    configuracao = sa.table(
        "configuracao_de_proposta",
        sa.column("proximo_numero", sa.Integer), sa.column("revisores", sa.JSON),
        sa.column("plano_bpo", sa.Numeric), sa.column("plano_plus", sa.Numeric), sa.column("plano_cfo", sa.Numeric),
        sa.column("criado_em", sa.DateTime(timezone=True)), sa.column("atualizado_em", sa.DateTime(timezone=True)),
    )
    agora = datetime.now(timezone.utc)
    op.bulk_insert(configuracao, [{
        "proximo_numero": 154, "revisores": ["Eduardo", "Karine"],
        "plano_bpo": 5000, "plano_plus": 7000, "plano_cfo": 9000,
        "criado_em": agora, "atualizado_em": agora,
    }])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposta_oportunidade_id'))

    op.drop_table('proposta')
    with op.batch_alter_table('matriz_de_proposta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matriz_de_proposta_tipo'))

    op.drop_table('matriz_de_proposta')
    op.drop_table('configuracao_de_proposta')
    # ### end Alembic commands ###
