"""motivo de encerramento

Revisão: 2042b068186f
Revisão anterior: b47a1eede16f
Criada em: 2026-09-26 15:43:31.515048
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '2042b068186f'
down_revision: str | None = 'b47a1eede16f'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_de_contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo_categoria', sa.Enum('Preço', 'Insatisfação com o serviço', 'Migrou para concorrente', 'Internalizou a operação', 'Empresa encerrada, vendida ou reestruturada', 'Inadimplência', 'Saída organizada pela Critério', 'Não precisa mais do serviço', 'Outro', name='motivodeencerramento', native_enum=False, length=60), nullable=True))
        batch_op.create_index(batch_op.f('ix_evento_de_contrato_motivo_categoria'), ['motivo_categoria'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_de_contrato', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evento_de_contrato_motivo_categoria'))
        batch_op.drop_column('motivo_categoria')

    # ### end Alembic commands ###
