"""contrato da carteira anterior e empresa

Revisão: 33f52c219e28
Revisão anterior: c6a727f3ba73
Criada em: 2026-09-26 16:11:59.111359
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '33f52c219e28'
down_revision: str | None = 'c6a727f3ba73'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('anterior_ao_crm', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.create_index(batch_op.f('ix_contrato_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_contrato_empresa_id_empresa'), 'empresa', ['empresa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_contrato_empresa_id_empresa'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contrato_empresa_id'))
        batch_op.drop_column('anterior_ao_crm')
        batch_op.drop_column('empresa_id')

    # ### end Alembic commands ###
