"""revisao da carteira

Revisão: e1a2564337e7
Revisão anterior: 1d8ac660302d
Criada em: 2026-09-27 08:14:17.111809
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = 'e1a2564337e7'
down_revision: str | None = '1d8ac660302d'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revisao_da_carteira',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes_de_referencia', sa.Date(), nullable=False),
    sa.Column('registrada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registrada_por', sa.String(length=120), nullable=False),
    sa.Column('isc_valor', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('isc_zona', sa.String(length=20), nullable=False),
    sa.Column('componente_classe', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('componente_semaforo', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('componente_churn', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('grupos', sa.Integer(), nullable=False),
    sa.Column('receita_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('grupos_travados', sa.Integer(), nullable=False),
    sa.Column('receita_travada', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('percentual_travado', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('baseado_em_referencia', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revisao_da_carteira')),
    sa.UniqueConstraint('mes_de_referencia', name='uq_revisao_carteira_mes')
    )
    with op.batch_alter_table('revisao_da_carteira', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revisao_da_carteira_mes_de_referencia'), ['mes_de_referencia'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revisao_da_carteira', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revisao_da_carteira_mes_de_referencia'))

    op.drop_table('revisao_da_carteira')
    # ### end Alembic commands ###
