"""eventos de contrato

Revisão: b47a1eede16f
Revisão anterior: 750ae400d08e
Criada em: 2026-09-26 15:32:12.900746
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = 'b47a1eede16f'
down_revision: str | None = '750ae400d08e'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento_de_contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('Aditivo', 'Reajuste', 'Expansão', 'Contração', 'Renovação', 'Encerramento', name='tipodeeventodecontrato', native_enum=False, length=40), nullable=False),
    sa.Column('data_do_evento', sa.Date(), nullable=False),
    sa.Column('registrado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('preco_mensal_anterior', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('preco_mensal_novo', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('preco_anual_anterior', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('preco_anual_novo', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('escopo_anterior', sa.String(length=200), nullable=True),
    sa.Column('escopo_novo', sa.String(length=200), nullable=True),
    sa.Column('data_fim_anterior', sa.Date(), nullable=True),
    sa.Column('data_fim_nova', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], name=op.f('fk_evento_de_contrato_contrato_id_contrato')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evento_de_contrato'))
    )
    with op.batch_alter_table('evento_de_contrato', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evento_de_contrato_contrato_id'), ['contrato_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evento_de_contrato_tipo'), ['tipo'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_de_contrato', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evento_de_contrato_tipo'))
        batch_op.drop_index(batch_op.f('ix_evento_de_contrato_contrato_id'))

    op.drop_table('evento_de_contrato')
    # ### end Alembic commands ###
