"""historico de preco e origem da volumetria

Revisão: 750ae400d08e
Revisão anterior: b3f1c9a7d2e4
Criada em: 2026-09-26 10:01:26.429721
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '750ae400d08e'
down_revision: str | None = 'b3f1c9a7d2e4'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico_de_preco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oportunidade_id', sa.Integer(), nullable=False),
    sa.Column('registrado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origem', sa.String(length=30), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('preco_mensal_anterior', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('preco_mensal_novo', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('preco_anual_anterior', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('preco_anual_novo', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['oportunidade_id'], ['oportunidade.id'], name=op.f('fk_historico_de_preco_oportunidade_id_oportunidade')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historico_de_preco'))
    )
    with op.batch_alter_table('historico_de_preco', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historico_de_preco_oportunidade_id'), ['oportunidade_id'], unique=False)

    with op.batch_alter_table('oportunidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origem_da_volumetria', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidade', schema=None) as batch_op:
        batch_op.drop_column('origem_da_volumetria')

    with op.batch_alter_table('historico_de_preco', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historico_de_preco_oportunidade_id'))

    op.drop_table('historico_de_preco')
    # ### end Alembic commands ###
