"""classificacao do grupo

Revisão: 6857edd15050
Revisão anterior: 26e2cc62ead2
Criada em: 2026-09-26 18:32:13.162102
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '6857edd15050'
down_revision: str | None = '26e2cc62ead2'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classificacao_do_grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.Date(), nullable=False),
    sa.Column('fonte', sa.String(length=200), nullable=False),
    sa.Column('versao_dos_parametros', sa.String(length=40), nullable=False),
    sa.Column('registrado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('receita_mensal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('margem', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('horas_por_mes', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rentabilidade_da_planilha', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('nota_receita', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('nota_rentabilidade', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('complexidade', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('disciplina', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('risco_tecnico', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('cross_sell', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('adimplencia', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('semaforo', sa.SmallInteger(), nullable=False),
    sa.Column('churn', sa.SmallInteger(), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('classe', sa.String(length=1), nullable=False),
    sa.Column('classe_efetiva', sa.String(length=20), nullable=False),
    sa.Column('alerta_de_churn', sa.String(length=1), nullable=True),
    sa.Column('em_cobranca', sa.Boolean(), nullable=False),
    sa.Column('eixo_de_acao', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_economico.id'], name=op.f('fk_classificacao_do_grupo_grupo_id_grupo_economico')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classificacao_do_grupo')),
    sa.UniqueConstraint('grupo_id', 'referencia', name='uq_classificacao_grupo_referencia')
    )
    with op.batch_alter_table('classificacao_do_grupo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classificacao_do_grupo_classe'), ['classe'], unique=False)
        batch_op.create_index(batch_op.f('ix_classificacao_do_grupo_eixo_de_acao'), ['eixo_de_acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_classificacao_do_grupo_grupo_id'), ['grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classificacao_do_grupo_referencia'), ['referencia'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classificacao_do_grupo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classificacao_do_grupo_referencia'))
        batch_op.drop_index(batch_op.f('ix_classificacao_do_grupo_grupo_id'))
        batch_op.drop_index(batch_op.f('ix_classificacao_do_grupo_eixo_de_acao'))
        batch_op.drop_index(batch_op.f('ix_classificacao_do_grupo_classe'))

    op.drop_table('classificacao_do_grupo')
    # ### end Alembic commands ###
